OnlineEdu.WebUI/Models/ErrorViewModel.cs
namespace OnlineEdu.WebUI.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

OnlineEdu.WebUI/Areas/Admin/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineEdu.WebUI.DTOs.AboutDtos;
using OnlineEdu.WebUI.Helpers;

namespace OnlineEdu.WebUI.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("[area]/[controller]/[action]/{id?}")]
	public class AboutController : Controller
	{
		private readonly HttpClient _client = HttpClientIntance.CreateClient();
		public async Task<IActionResult> Index()
		{
			var values = await _client.GetFromJsonAsync<List<ResultAboutDto>>("abouts");
			return View(values);
		}
		public async Task<IActionResult> DeleteAbout(int id)
		{
			await _client.DeleteAsync($"abouts/{id}");
			return RedirectToAction(nameof(Index));
		}
		public IActionResult CreateAbout()
		{ 
			return View(); 
		}
		[HttpPost]
		public async Task<IActionResult> CreateAbout(CreateAboutDto createAboutDto)
		{
			await _client.PostAsJsonAsync("abouts", createAboutDto);
			return RedirectToAction(nameof(Index));
		}
		public async Task<IActionResult> UpdateAbout(int id)
		{
			var values = await _client.GetFromJsonAsync<UpdateAboutDto>($"abouts/{id}");
			return View(values);
		}
		[HttpPost]
		public async Task<IActionResult> UpdateAbout(UpdateAboutDto updateAboutDto)
		{
			await _client.PutAsJsonAsync("abouts", updateAboutDto);
			return RedirectToAction(nameof(Index));
		}
	}
}

OnlineEdu.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineEdu.WebUI.Models;
using System.Diagnostics;

namespace OnlineEdu.WebUI.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

OnlineEdu.WebUI/Areas/Admin/Views/About/CreateAbout.cshtml
@model CreateAboutDto
@{
    ViewData["Title"] = "Yeni Hakkımda Oluşturma Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form method="post">
    <label>Açıklama</label>
    <textarea asp-for="Description" class="form-control" rows="5"></textarea>
    <br />
    <label>Resim Url 1</label>
    <input type="text" asp-for="ImageUrl1" class="form-control" />
    <br />
    <label>Resim Url 2</label>
    <input type="text" asp-for="ImageUrl2" class="form-control" />
    <br />
    <label>Madde 1</label>
    <input type="text" asp-for="Item1" class="form-control" />
    <br />
    <label>Madde 2</label>
    <input type="text" asp-for="Item2" class="form-control" />
    <br />
    <label>Madde 3</label>
    <input type="text" asp-for="Item3" class="form-control" />
    <br />
    <label>Madde 4</label>
    <input type="text" asp-for="Item4" class="form-control" />
    <br />
    <button class="btn btn-outline-primary">Kaydet</button>
</form>

OnlineEdu.WebUI/Areas/Admin/Views/About/Index.cshtml
@model List<ResultAboutDto>
@{
    ViewData["Title"] = "Hakkımda Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    int count = 0;
}
<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Resim1</th>
        <th>Resim2</th>
        <th>Açıklama</th>
        <th>Madde1</th>
        <th>Madde2</th>
        <th>Madde3</th>
        <th>Madde4</th>
    </tr>
    @foreach(var item in Model)
    {
        count++;
        <tr>
            <th>@count</th>
            <td><img src="@item.ImageUrl1" style="height:75px;width:75px" /></td>
            <td><img src="@item.ImageUrl2" style="height:75px;width:75px" /></td>
            <td>@item.Description</td>
            <td>@item.Item1</td>
            <td>@item.Item2</td>
            <td>@item.Item3</td>
            <td>@item.Item4</td>
            <td>
                <a asp-action="DeleteAbout" asp-controller="About" asp-area="Admin" asp-route-id="@item.AboutId" class="btn btn-outline-danger">Sil</a>
                <a asp-action="UpdateAbout" asp-controller="About" asp-area="Admin" asp-route-id="@item.AboutId" class="btn btn-outline-info">Güncelle</a>
            </td>
        </tr>
      
    }

</table>
<br />
<a asp-action="CreateAbout" asp-controller="About" asp-area="Admin" class="btn btn-outline-primary">Yeni Hakkımda Ekle</a>

OnlineEdu.WebUI/Areas/Admin/Views/About/UpdateAbout.cshtml
@model UpdateAboutDto
@{
    ViewData["Title"] = "Hakkımda Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<form method="post">
    <input type="hidden" asp-for="AboutId" />
    <label>Açıklama</label>
    <textarea asp-for="Description" class="form-control" rows="5"></textarea>
    <label>Resim Url 1</label>
    <input type="text" asp-for="ImageUrl1" class="form-control" />
    <label>Resim Url 2</label>
    <input type="text" asp-for="ImageUrl2" class="form-control" />
    <label>Madde 1</label>
    <input type="text" asp-for="Item1" class="form-control" />
    <label>Madde 2</label>
    <input type="text" asp-for="Item2" class="form-control" />
    <label>Madde 3</label>
    <input type="text" asp-for="Item3" class="form-control" />
    <label>Madde 4</label>
    <input type="text" asp-for="Item4" class="form-control" />
    <br />
    <button class="btn btn-outline-primary">Güncelle</button>
</form>

OnlineEdu.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OnlineEdu.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineEdu.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineEdu.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineEdu.WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OnlineEdu.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>